#!/usr/bin/env bash
# =============================================================================
# adapters/kimi-cli/adapter.sh — Kimi Code CLI platform adapter
# =============================================================================
# Sourced by scripts/build.sh AFTER adapters/lib.sh.
#
# Kimi Code CLI (Moonshot AI) natively supports Agent Skills: a directory
# containing a SKILL.md is discovered under .kimi/skills/ (project) or
# ~/.kimi/skills/ (user). So the skill ships as a native Kimi skill rather
# than a loose dispatcher file.
#
# Kimi has no user-defined slash commands (only a built-in set), so SKILL.md
# doubles as the dispatcher: it carries an auto-generated routing table that
# maps natural-language triggers to command files under commands/.
#
# Hooks (PreToolUse/PostToolUse/PostCompact/...) are configured in
# ~/.kimi/config.toml via [[hooks]] blocks; we ship the hook scripts plus a
# ready-to-append kimi-hooks.toml snippet.
# =============================================================================

KIMI_PLATFORM="kimi-cli"
KIMI_DIR="kimi"
KIMI_SKILL="obsidian-second-brain"

# adapter_build <src_root> <dst_root>
adapter_build() {
  local src="$1" dst="$2"
  local skill_dir="$dst/.${KIMI_DIR}/skills/$KIMI_SKILL"

  _kimi_emit_skill        "$src" "$skill_dir"
  _kimi_translate_commands "$src/commands"   "$skill_dir/commands"
  _kimi_copy_references    "$src/references" "$skill_dir/references"
  _kimi_copy_scripts       "$src/scripts"    "$skill_dir/scripts"
  _kimi_emit_hooks         "$src/hooks"      "$dst"
  _kimi_emit_install_hint  "$dst"
}

# Emit SKILL.md — the Kimi skill manifest and dispatcher in one file.
# Frontmatter is reused verbatim from the repo's SKILL.md (name/description),
# then the body is a Kimi operating manual + auto-generated routing tables.
_kimi_emit_skill() {
  local src="$1" skill_dir="$2"
  local out="$skill_dir/SKILL.md"
  mkdir -p "$skill_dir"

  {
    # Frontmatter copied verbatim from the source SKILL.md (name + description).
    echo "---"
    awk '/^---$/{c++; next} c==1{print} c>=2{exit}' "$src/SKILL.md"
    echo "---"

    cat <<'EOF'

# Obsidian Second Brain — Kimi Code CLI skill

This skill operates an Obsidian vault as a self-rewriting second brain. It
ships a set of *commands*: each one is a multi-step instruction file you (the
Kimi agent) follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily note format, naming, propagation
   rules). It is the operating manual for this vault.
2. When the user's request matches a trigger in the tables below, read the
   matching file under `commands/<name>.md` (inside this skill directory) and
   follow its instructions step by step.
3. Kimi Code CLI has no user-defined slash commands. The `/name` form in the
   tables is a label, not a command you can run — match on the natural-language
   triggers instead. If the user types `/name` literally, treat it as a request
   for that command.
4. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## For future Claude` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.
5. Do not invent commands. If no command matches, ask the user what they want
   or fall back to plain natural-language help.

## Command routing tables (grouped by category)
EOF

    emit_routing_table_grouped "$src/commands" "$KIMI_PLATFORM" "commands"
    emit_trigger_reference     "$src/commands" "$KIMI_PLATFORM"

    cat <<'EOF'

## Scripts

Python helpers live under `scripts/` inside this skill directory. They run via
`uv run -m scripts.research.<name>` from the vault root (or wherever the skill
is installed). The commands that need them reference the exact invocation
inside the command body.

## Hooks (optional, Layer 5)

Two hook scripts ship alongside this skill under `.kimi/hooks/`:

- `obsidian-bg-agent.sh` — `PostCompact` hook. After context compaction it runs
  a headless `kimi --print` agent that propagates session findings to the vault.
- `validate-ai-first.sh` — `PostToolUse` hook on file writes. Warns (non-blocking)
  when a vault note fails the AI-first rule.

Wire them up by appending `kimi-hooks.toml` (shipped at the dist root) to your
`~/.kimi/config.toml`. See `INSTALL.md` for details.

---

*Generated by adapters/kimi-cli/adapter.sh — do not edit manually.*
EOF
  } > "$out"
}

# Copy commands into the skill's commands/, neutralizing Claude-specific tool
# names and rewriting .claude/ paths to .kimi/ so the instructions still make
# sense for Kimi Code CLI agents.
_kimi_translate_commands() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  local f out
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$KIMI_PLATFORM" || continue
    out="$dst/$(basename "$f")"
    cp "$f" "$out"
    rewrite_tool_neutral "$out"
    rewrite_platform_paths "$out" "$KIMI_DIR"
  done
}

_kimi_copy_references() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
  find "$dst" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    rewrite_platform_paths "$f" "$KIMI_DIR"
  done
}

_kimi_copy_scripts() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
}

# Ship the hook scripts under .kimi/hooks/ and emit a kimi-hooks.toml snippet
# the user appends to ~/.kimi/config.toml. The PostCompact background agent is
# rewritten from `claude -p` to Kimi's headless `kimi --print` mode.
_kimi_emit_hooks() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  local hooks_dst="$dst/.${KIMI_DIR}/hooks"
  mkdir -p "$hooks_dst"

  # Background agent — rewrite headless invocation and setup comments for Kimi.
  if [[ -f "$src/obsidian-bg-agent.sh" ]]; then
    cp "$src/obsidian-bg-agent.sh" "$hooks_dst/obsidian-bg-agent.sh"
    # `kimi --print` runs headless; `--yolo` auto-approves tool calls so the
    # background agent can write to the vault without a prompt (the Kimi
    # equivalent of Claude's `--dangerously-skip-permissions`).
    perl -i -pe '
      s{claude --dangerously-skip-permissions -p}{kimi --print --yolo}g;
      s{\Q~/.claude/settings.json\E}{~/.kimi/config.toml}g;
      s{PostCompact hook in ~/\.kimi/config\.toml}{[[hooks]] block in ~/.kimi/config.toml}g;
    ' "$hooks_dst/obsidian-bg-agent.sh"
    chmod +x "$hooks_dst/obsidian-bg-agent.sh"
  fi

  # AI-first validator — Kimi PostToolUse payload uses .tool_input.file_path,
  # which the script already reads. No rewrite needed.
  if [[ -f "$src/validate-ai-first.sh" ]]; then
    cp "$src/validate-ai-first.sh" "$hooks_dst/validate-ai-first.sh"
    chmod +x "$hooks_dst/validate-ai-first.sh"
  fi

  cat > "$dst/kimi-hooks.toml" <<'EOF'
# obsidian-second-brain — hooks for Kimi Code CLI
# =============================================================================
# Append these blocks to ~/.kimi/config.toml (user-level) or to a project-level
# .kimi/config.toml. Adjust the `command` paths to wherever you installed the
# hook scripts (INSTALL.md uses ~/.kimi/hooks/).
# =============================================================================

# Layer 5a — warn when a vault note breaks the AI-first rule (non-blocking).
[[hooks]]
event = "PostToolUse"
matcher = "WriteFile|StrReplaceFile"
command = "~/.kimi/hooks/validate-ai-first.sh"
timeout = 10

# Layer 5b — after context compaction, propagate session findings to the vault.
[[hooks]]
event = "PostCompact"
command = "~/.kimi/hooks/obsidian-bg-agent.sh"
timeout = 30
EOF
}

_kimi_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on Kimi Code CLI

Kimi Code CLI discovers Agent Skills under `.kimi/skills/` (project) and
`~/.kimi/skills/` (user). This build ships `obsidian-second-brain` as a native
Kimi skill.

## 1. Install the skill

```bash
# From the repo root, after `bash scripts/build.sh --platform kimi-cli`.
# User-level (available in every vault):
mkdir -p ~/.kimi/skills
cp -R dist/kimi-cli/.kimi/skills/obsidian-second-brain ~/.kimi/skills/

# OR project-level (this vault only) — copy into the vault root instead:
cp -R dist/kimi-cli/.kimi /path/to/your/vault/
```

The skill auto-loads when relevant; you can also load it explicitly with
`/skill:obsidian-second-brain`. Because Kimi has no user-defined slash
commands, the `/obsidian-*` commands are matched by natural-language triggers
listed in `SKILL.md`.

## 2. Wire up the hooks (optional — Layer 5)

```bash
mkdir -p ~/.kimi/hooks
cp dist/kimi-cli/.kimi/hooks/* ~/.kimi/hooks/
chmod +x ~/.kimi/hooks/*.sh
```

Append the contents of `dist/kimi-cli/kimi-hooks.toml` to `~/.kimi/config.toml`,
then set `OBSIDIAN_VAULT_PATH` (env var or `~/.kimi/config.toml` env section) to
your vault path. View active hooks anytime with the `/hooks` slash command.

Notes:

- `validate-ai-first.sh` (PostToolUse) works as-is — Kimi passes the written
  path as `.tool_input.file_path`.
- `obsidian-bg-agent.sh` (PostCompact) runs a headless `kimi --print` agent.
  It expects the compaction payload to expose a transcript path; if Kimi's
  payload differs, the hook exits silently without changes (safe no-op).
  Verify your Kimi version's headless permission flags before relying on it.

## 3. Scripts

`scripts/` inside the skill holds the Python research helpers. Run them via
`uv run -m scripts.research.<name>` from the vault root. They need the API
keys documented in the repo README.

Start Kimi Code CLI from the vault root.
EOF
}
